### ISSUE TITLE
The website does not load the font for the texts

### ISSUE THREAD

**Issue by haneenmahd** [evercode-io/evercode-website#2]
The Circular Font Does not load On The Website.
[Link](http://evercode-test.netlify.app/)

**Comment by vsrawat1998** [comment]
Hey,
/static/media/circular-medium.9ffafedd.otf
This is how your css imports the circular fonts but the media folder is empty.
You can refer to this
https://community.netlify.com/t/custom-fonts-in-src-assets-fonts-headers-access-control-problems/27639

**Comment by haneenmahd** [comment]
> Hey,
> /static/media/circular-medium.9ffafedd.otf
> This is how your css imports the circular fonts but the media folder is empty.
> You can refer to this
> https://community.netlify.com/t/custom-fonts-in-src-assets-fonts-headers-access-control-problems/27639

Let me try🤗

**Comment by haneenmahd** [comment]
Fixed the issue from the PR #4
